# Generated by Django 2.1.1 on 2018-09-21 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RFID', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RfidData',
            new_name='RFID',
        ),
    ]
