# Generated by Django 2.1.1 on 2018-09-21 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RFID', '0002_auto_20180922_0437'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RFID',
        ),
    ]
