# Generated by Django 2.1.1 on 2018-09-22 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RFID', '0004_rfiddb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rfiddb',
            old_name='name',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='rfiddb',
            name='serial',
            field=models.IntegerField(default=0),
        ),
    ]
