# Generated by Django 2.1.1 on 2018-09-25 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RFID', '0005_auto_20180922_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField(default=0)),
                ('status', models.CharField(max_length=10)),
                ('time', models.CharField(max_length=20)),
            ],
        ),
    ]
